{{- if .Values.db.enabled }}
{{- range $index, $user := .Values.db.mongodbCommunity.users }}
{{- if gt $index 0 }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $user.passwordSecretRef.name }}
type: Opaque
stringData:
  password: {{ $.Values.secret.password }}
{{- end }}
{{- end }}