apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-secrets
type: {{ .Values.web.secret.type }}
data:
  mongodbAdminUsername: {{ .Values.web.secret.mongodbAdminUsername | b64enc }}
  mongodbAdminPassword: {{ .Values.web.secret.mongodbAdminPassword | b64enc }}
{{- if and .Values.web.basicAuth.enabled (not .Values.web.oidc.enabled) }}
  basicAuthUsername: {{ .Values.web.basicAuth.username | b64enc }}
  basicAuthPassword: {{ .Values.web.basicAuth.password | b64enc }}
{{- end }}
{{- if .Values.web.secret.sessionSecret }}
  sessionSecret: {{ .Values.web.secret.sessionSecret | b64enc }}
{{- end }}
{{- if .Values.web.secret.cookieSecret }}
  cookieSecret: {{ .Values.web.secret.cookieSecret | b64enc }}
{{- end }}
{{- if and .Values.web.oidc.enabled .Values.web.oidc.clientSecret }}
  oidcClientSecret: {{ .Values.web.oidc.clientSecret | b64enc }}
{{- end }}
{{- if and .Values.web.oidc.enabled .Values.web.oidc.secret }}
  oidcSecret: {{ .Values.web.oidc.secret | b64enc }}
{{- end }}
